name: focused_image_widget
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/10urbulut/focused_image_widget

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
